name: release
description: Release a new version of the project
author: shiipou
branding:
  color: green
  icon: tag

inputs:
  version:
    description: 'The version to release'
    required: true
  changelogs:
    description: 'The changelogs to include in the release'
    required: false
    default: ''
  pre-release:
    description: 'Whether to release a pre-release or not'
    required: false
    default: 'false'
  assets:
    description: 'The path to the assets to upload with the release'
    required: false
    default: ''
  github-token:
    description: 'The GitHub token to use to authenticate to the GitHub API'
    required: true

runs:
  using: "composite"
  steps:
    - name: Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CHANGELOGS: ${{ inputs.changelogs }}
      run: |
        changelog_file=$(mktemp)
        echo "${CHANGELOGS}" > "$changelog_file"

        ARGS="--repo ${{ github.repository }} --target ${{ github.sha }} -F $changelog_file"
        if ${{ inputs.pre-release }} ; then
          ARGS="$ARGS --prerelease"
        fi

        assets="${{ inputs.assets }}"
        if [ -z "$assets" ]; then
          assets="$(find artifacts/ -type f -printf "%p ")"
        fi
        echo "$assets"
        
        gh release create $ARGS "v${{ inputs.version }}" $assets
