name: Release

on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha

permissions:
  contents: write

jobs:
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
      
  release:
    needs: get-version
    if: ${{ needs.get-version.outputs.version != '' }}
    uses: shiipou/github-actions/.github/workflows/upsert-release.yml@main
    with:
      version: ${{ needs.get-version.outputs.version }}
      changelog: ${{ needs.get-version.outputs.changelog }}
      prerelease: ${{ needs.get-version.outputs.channel != '' }}
