name: Release

on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha

permissions:
  contents: write

jobs:
  release:
    uses: shiipou/github-actions/.github/workflows/release.yml@main
