name: Build Flutter

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: 'The directory where to run the action'
        required: false
        default: '.'
      package-name:
        type: string
        description: 'Name of the package to deploy'
        required: true
      version:
        type: string
        description: 'Version of the package to deploy'
        required: true
      build:
        type: string
        description: 'Build number of the package to deploy'
        required: true
      flutter-version:
        type: string
        description: 'Version of Flutter to use'
        required: false
        default: '3.10.x'
      flutter-channel:
        type: string
        description: 'Channel of Flutter to use'
        required: false
        default: 'stable'
      platform:
        type: string
        description: 'Platform where to build the app (linux,android,...)'
        required: true
      targets:
        type: string
        description: 'Target file extension to build (exe,apk,...)'
        required: true
      runner:
        type: string
        description: 'The runner to use to build the app (ubuntu-latest, ....)'
        required: true
      flutter-extra-args:
        type: string
        description: 'Extra build args to pass to the flutter_distributor commands'
        required: false
        default: ''
      artifacts:
        type: string
        description: 'Path to the artifacts build by the action (dist/macos/*.{zip,dmg})'
        required: true
    secrets:
      upload-key-store:
        description: The keystore file to sign the app
        required: false
      upload-key-name:
        description: The name of the key to sign the app
        required: false
      upload-key-password:
        description: The password of the key to sign the app
        required: false
      service-account-json:
        description: The token that'll authentificate the user to the Google Playstore API to create new release
        required: false

jobs:
  build:
    name: Build ${{ matrix.platform }}
#     strategy:
#       matrix:
#         platform: [ web, windows, linux, macos, android, ios ]
#         include:
#           - platform: web
#             targets: zip
#             runner: ubuntu-latest
#             artifacts: dist/web/*.zip
#           - platform: linux
#             targets: zip,deb,rpm,appimage
#             runner: ubuntu-latest
#             artifacts: dist/linux/*.{zip,deb,rpm,AppImage}
#           - platform: android
#             targets: apk,aab
#             runner: ubuntu-latest
#             artifacts: dist/android/*.{apk,aab}
#           - platform: windows
#             targets: zip,exe,msix
#             runner: windows-latest
#             artifacts: dist/windows/*.{zip,exe,msix}
#           - platform: macos
#             targets: zip,dmg
#             runner: macos-latest
#             artifacts: dist/macos/*.{zip,dmg}
#           - platform: ios
#             targets: ipa
#             runner: macos-latest
#             artifacts: dist/ios/*.ipa
    runs-on: ${{ inputs.runner }}
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Assign Keystore
        if: runner.os == 'Linux'
        uses: shiipou/github-actions/jobs/android-keystore@main
        with:
          working-directory: './android'
          upload-key-store: ${{ secrets.upload-key-store }}
          upload-key-name: ${{ secrets.upload-key-name }}
          upload-key-password: ${{ secrets.upload-key-password }}

      - name: Build
        uses: shiipou/github-actions/jobs/build-flutter@main
        with:
          version: ${{ inputs.version }}
          build: ${{ inputs.build }}
          platform: ${{ inputs.platform }}
          targets: ${{ inputs.targets }}
          flutter-extra-args: ${{ inputs.flutter-extra-args }}
          flutter-version: ${{ inputs.flutter-version }}
          flutter-channel: ${{ inputs.flutter-channel }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.platform }}
          path: ${{ inputs.artifacts }}
