name: Build Docker Image
# description: Build a Docker image with a prebuild artifact included.

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: 'Directory containing the Dockerfile'
        required: false
        default: '.'
      tags:
        type: string
        description: 'Comma separated list of Tag for the docker image'
        required: true
      dockerfile:
        type: string
        description: 'Dockerfile path to use in the docker build command'
        required: false
        default: 'Dockerfile'
      with-artifact-name:
        type: string
        description: 'Name of the artifact to include in the image'
        required: false
      with-artifact-path:
        type: string
        description: 'Where to place the artifacts'
        required: false
        default: 'artifacts/'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        if: inputs.with-artifact-name != ''
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.with-artifact-name }}
          path: ${{ inputs.working-directory }}/${{ inputs.with-artifact-path }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
